# Set the default profile to use when none are specified
spring.profiles.active=dev
spring.application.name=GlitchDex
# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
# Server Configuration
server.port=8080
# Internationalization
spring.messages.basename=templates/messages
spring.messages.encoding=UTF-8
# Credentials
glitchdex.admin.email=admin@glitchdex.com
glitchdex.admin.password=supersecretpassword
# Storage
storage.location=uploads