logging.level.br.ufscar.glitchdex=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=INFO

# Set the default profile to use when none are specified
spring.profiles.active=dev
spring.application.name=GlitchDex
# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
# Server Configuration
spring.jpa.open-in-view=false
server.port=8080
spring.servlet.multipart.max-file-size=10MB
# Internationalization
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.messages.basename=templates/messages
spring.messages.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8
# Credentials
glitchdex.admin.email=admin@glitchdex.com
glitchdex.admin.password=supersecretpassword
# Storage
storage.location=uploads
# Available Languages
glitchdex.languages=en,pt,es,fr,it,de,zh,ja,ru


