spring.datasource.url=jdbc:h2:mem:glitchdexdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'create-drop' is perfect for development, as the DB is wiped clean on each restart
spring.jpa.hibernate.ddl-auto=create-drop
# Explicitly disable Docker Compose integration when the 'dev' profile is active
spring.docker.compose.enabled=false
# Logging Configuration
logging.level.org.springframework=INFO
logging.level.br.ufscar.glitchdex=DEBUG
server.error.include-stacktrace=never
# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false